### ISSUE TITLE
Can not extract comments when assigning to variable

### ISSUE THREAD

**Issue by NervosaX** [connectedcars/gettext-extractor#4]
I'm having difficulty extracting comments above a gettext extraction when assigning it to a variable first.

Here is a breaking test:

Modifying https://github.com/lukasgeiter/gettext-extractor/blob/master/tests/js/extractors/comments.test.ts

```javascript
    const LEADING_LINE_AND_TRAILING_LINE = `
            // Leading line comment
            getText('Foo'); // Trailing line comment
        `;
```

to 

```javascript
    const LEADING_LINE_AND_TRAILING_LINE = `
            // Leading line comment
            var myTranslation = getText('Foo'); // Trailing line comment
        `;
```

breaks the test.

**Comment by lukasgeiter** [comment]
Thank you for reporting this bug! It's actually an I found recently myself.

I'm currently working on a solution but it will likely take quite a bit of time for development and testing...
The problem is that the extractor basically has to understand when a comment belongs to a call expression or not. Taking the example with an assignment and adding an additional one:

```
var foo = getText('Foo'); // Comment
```

```
var foo = getText('Foo'),
      bar = 42; // Comment
```

Now for the developer it's clear that while in the first example the comment belongs to message, in the second it doesn't. When going trough the AST however, it's not so easy to figure that out. Of course it's possible to do, but the challenge is to keep it relatively generic while avoiding all kinds of false positives.

Anyway, I'm working on it and will update this issue once I have a fix ready.

**Comment by lukasgeiter** [comment]
I've significantly improved the extraction of comments in the latest release. In version 2.1.0, the context of the expression is taken into account which means comments, including those around variable declarations, are extracted much more intelligently.
