### ISSUE TITLE
Update typescript dependency requirement 

### ISSUE THREAD

**Issue by Kjagd** [connectedcars/gettext-extractor#43]
Since typescript is required in version `2-4`, it doesn't support any minor or patch versions of the latest typescript.

![billede](https://user-images.githubusercontent.com/1812228/98661386-ace05d00-2346-11eb-9a42-34619208e31f.png)

https://github.com/lukasgeiter/gettext-extractor/blob/master/package.json#L41

I'm not sure if it could be a devDep only, or if the range should just be widened.

Thanks.

**Comment by lukasgeiter** [comment]
The range `2 - 4` actually includes all minor and patch versions of TypeScript 4. You can easily see all included versions using the official [npm semantic version calculator](https://semver.npmjs.com/). (Just make sure to write the spaces around the minus)

From the screenshot you posted I can't really tell what the problem is. If you need further help, please provide more details or ideally a repository that reproduces the issue.

**Comment by Kjagd** [comment]
Hi, thanks for the quick reply. You are right of course - I was in the process of updating from node 14 to 15 and it seems like the resolutions logic and output is a bit different and I jumped the gun on the semver range, while it's actually another project using `    "typescript": "^3.5.3"` which causes this. Anyways thanks for the library, it's very useful.
