### ISSUE TITLE
Create a CLI to complement your lib

### ISSUE THREAD

**Issue by sinedied** [connectedcars/gettext-extractor#8]
Just tried your lib, it works perfectly for my use case with TypeScript/node-gettext 👍 

Your lib is great, but it would be even better if there was a CLI with it that use some json config (either in a standalone `.gettext-extract` or directly embedded in `package.json`).

Are you open for a PR on this? Or do you prefer if I create a separate project for the CLI?

Thanks again for the great work.

**Comment by lukasgeiter** [comment]
Glad the hear that 🙂 

I decided against using a plain JSON config because I wanted the library to be a s flexible and possible but still easy to use. If you have a suggestion for a JSON config structure, that covers all functionality, I might change my mind.

In any case I would probably implement it as a separate package.

**Comment by sinedied** [comment]
I just published the first version of the CLI, here is the repo: https://github.com/sinedied/gettext-extract
As for the JSON structure, I mapped it on your API as close as possible, with (very) few simplifications. Feel free to comment on this 😉 

At least it works for my use case and the config can be integrated within the `package.json` file (both the tool config and the npm script to run it).
